### ISSUE TITLE
SSL errors without ability to ignore

### ISSUE THREAD

**Issue by unovongalixor** [ecmwf/cdsapi#33] opened 2020-12-17 12:05 UTC
I'm currently getting the following error while using the cdsapi and i can't find a way to ignore ssl errors.

WARNING:cdsapi:Recovering from connection error [HTTPSConnectionPool(host='136.156.132.235', port=443): Max retries exceeded with url: /cache-compute-0000/cache/data4/adaptor.mars.internal-1608196857.3120284-11250-14-fe304c3c-021b-42ef-824b-9d38937d9338.nc (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))], attemps 0 of 500
WARNING:cdsapi:Retrying in 120 seconds
INFO:cdsapi:Retrying now...

Can we get a way to silence and ignore ssl errors?

**Comment by pz-max** [comment] 2021-11-22 23:59
@unovongalixor having the same error. Should be a usage error. Did you solve it?

**Comment by JensvandeZande** [comment] 2021-11-23 07:47
@unovongalixor Also have the same error. @pz-max, what do you mean by "should be a usage error"?

**Comment by pz-max** [comment] 2021-11-23 08:45
@JensvandeZande thought the error was related to the local setup/setting (Vscode etc). But this is probably not the case since the example works:
```
$ python
>>> import cdsapi
>>> cds = cdsapi.Client()
>>> cds.retrieve('reanalysis-era5-pressure-levels', {
           "variable": "temperature",
           "pressure_level": "1000",
           "product_type": "reanalysis",
           "date": "2017-12-01/2017-12-31",
           "time": "12:00",
           "format": "grib"
       }, 'download.grib')
```

Btw, I just realise that the error is not exactly the same, but I think the error has a similar root.

WARNING:cdsapi:Recovering from connection error [HTTPSConnectionPool(host='download-0002.copernicus-climate.eu', port=443): Max retries exceeded with url: /cache-compute-0002/cache/data5/adaptor.mars.internal-1637617694.6830564-3826-4-dbe6c8b1-2f7f-453a-8eee-bb2b4fc17a83.nc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))], attemps 4 of 500
WARNING:cdsapi:Retrying in 120 seconds

**Comment by JensvandeZande** [comment] 2021-11-23 09:33
@pz-max I have somewhat the same error as you:

WARNING Recovering from connection error [HTTPSConnectionPool(host='download-0010.copernicus-climate.eu', port=443): Max retries exceeded with url: /cache-compute-0010/cache/data1/adaptor.mars.internal-1637610017.143116-2964-3-7d6c49bb-a593-44ae-b9fb-5ce678648e4f.nc (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))], attemps 46 of 500
2021-11-23 09:28:12,547 WARNING Retrying in 120 seconds
2021-11-23 09:30:12,640 INFO Retrying now...

I am using the same code I used for the last couple of days which worked perfectly fine. So maybe something wrong at the API side?

**Comment by pz-max** [comment] 2021-11-23 10:00
@JensvandeZande a colleague was reporting the same issue just right now.
https://confluence.ecmwf.int/pages/viewpage.action?pageId=242075914 
My colleague was lucky and it worked with server 0000. So maybe an error/invalid certificate of the server 0004 and checking above also an error of 0002,0010

**Comment by JensvandeZande** [comment] 2021-11-23 11:18
@pz-max many thanks for the heads up! Lets hope it gets sorted quickly. Nothing we can do ourselves right?

**Comment by pz-max** [comment] 2021-11-23 11:20
I am not aware of a fix
________________________________

**Comment by EddyCMWF** [comment] 2021-11-23 12:07
Hi All,
(Member of the CDS team)
There was an SSL certificate issue with some of our download nodes, this should now have been rectified.
Thanks,
Eddy

**Comment by mmichelli** [comment] 2022-04-20 10:48
I am getting this issue; it started this afternoon.

**Comment by EddyCMWF** [comment] 2022-04-27 12:57
Hi @mmichelli ,
(apologies for the slow response)
Can you confirm if you are still experiencing this issue? It is not really an issue with the cdsapi software, but a temporary issue with the CDS infrastructure. I believe this has been fixed and downloads are working again.
Thanks,
Eddy

**Comment by mmichelli** [comment] 2022-04-27 17:30
Yes, it's working now :)

**Comment by jdtuck** [comment] 2022-07-20 19:31
I just started to get SSL errors again now, that it is expired. Anybody else having these issues?

**Comment by Crissan85** [comment] 2022-08-10 04:40
HI
I am trying to run the following example [https://cds.climate.copernicus.eu/toolbox/doc/gallery/2_plot_map.html](url)
but I'm getting a similar error..
Anyone can run it with no problem?

**Comment by EddyCMWF** [comment] 2022-08-10 07:27
Hi @Crissan85, this example is for the cds-toolbox, not the cdsapi, I just checked and it running fine there.
Hi @jdtuck, I have not seen any SSL errors recently so I hope any issues have cleared up.

FYI, you will get a faster response if you use the CDS user support channels regarding service and troubleshooting issues:
https://cds.climate.copernicus.eu/cdsapp#!/usersupport

**Comment by EddyCMWF** [comment] 2022-08-10 07:51
As the SSL and HTTP issues are generally due to temporary connection issues, and not the cdsapi software, I am closing this ticket and advise future queries to be directed at the CDS user support channels where there is up to date information on any service issues and staff at hand to answer these sort of problems.
https://cds.climate.copernicus.eu/cdsapp#!/usersupport
Many thanks,
Eddy

**Closed** 2022-08-10 07:51 UTC

**Comment by PaulMI97** [comment] 2022-10-09 12:14
Goodmorning everyone, I am getting the same issue. @EddyCMWF can you confirm that it is a temporary issue with the CDS infrastructure and it doesn't concern the software

>>> import cdsapi
>>> cds = cdsapi.Client()
>>> cds.retrieve('reanalysis-era5-pressure-levels', {
...            "variable": "temperature",
...            "pressure_level": "1000",
...            "product_type": "reanalysis",
...            "date": "2017-12-01/2017-12-31",
...            "time": "12:00",
...            "format": "grib"
...        }, 'download.grib')
2022-10-09 14:02:13,688 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2022-10-09 14:02:13,870 INFO Request is queued
2022-10-09 14:02:14,906 INFO Request is completed
2022-10-09 14:02:14,906 INFO Downloading https://download-0018.copernicus-climate.eu/cache-compute-0018/cache/data9/adaptor.mars.internal-1664828501.7764702-7144-2-7c107ec3-1c3e-4c30-ae1c-3ebdf5ceec20.grib to download.grib (61.4M)
2022-10-09 14:02:15,018 WARNING Recovering from connection error [HTTPSConnectionPool(host='download-0018.copernicus-climate.eu', port=443): Max retries exceeded with url: /cache-compute-0018/cache/data9/adaptor.mars.internal-1664828501.7764702-7144-2-7c107ec3-1c3e-4c30-ae1c-3ebdf5ceec20.grib (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))], attemps 0 of 500
2022-10-09 14:02:15,019 WARNING Retrying in 120 seconds

**Comment by amstoner** [comment] 2022-10-09 17:14
I'm getting the same warning trying to download ERA5-Land data:

2022-10-09 11:46:56,598 INFO Welcome to the CDS
2022-10-09 11:46:56,598 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-land
2022-10-09 11:46:56,802 INFO Request is queued
2022-10-09 11:46:57,968 INFO Request is completed
2022-10-09 11:46:57,968 INFO Downloading https://download-0011-clone.copernicus-climate.eu/cache-compute-0011/cache/data6/adaptor.mars.internal-1665267287.7759356-21237-3-a39e598e-d21c-4b84-bb83-a7b008ef6a7c.nc to era5-land_temperature_1950.nc (105.8G)
2022-10-09 11:46:58,444 WARNING Recovering from connection error [HTTPSConnectionPool(host='download-0011-clone.copernicus-climate.eu', port=443): Max retries exceeded with url: /cache-compute-0011/cache/data6/adaptor.mars.internal-1665267287.7759356-21237-3-a39e598e-d21c-4b84-bb83-a7b008ef6a7c.nc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))], attemps 0 of 500
2022-10-09 11:46:58,445 WARNING Retrying in 120 seconds

**Comment by PaulMI97** [comment] 2022-10-10 07:05
@amstoner I tried again this morning and it worked without touching anything on my laptop or the software.

**Comment by amstoner** [comment] 2022-10-10 14:08
@PaulMI97 Thank you for letting me know! My script is downloading files now too!

**Comment by akrherz** [comment] 2023-10-05 17:49
I hate to bump a closed issue, but we are hitting this now and wondering about an option to ignore SSL cert issues.

At the moment `download-0001-clone.copernicus-climate.eu` had its cert updated last month, but is not providing the Intermediate CA.  You can see the issue reported at [ssllabs test](https://www.ssllabs.com/ssltest/analyze.html?d=download-0001-clone.copernicus-climate.eu)

**Comment by EddyCMWF** [comment] 2023-10-17 12:19
Hi @akrherz ,

We are unlikely to ignore SSL cert issues within the download methods in the cdsapi. However, it is possible for you to use your own downloading methods which ignore the SSL certificates. If you do not pass a target file in your cdsapi retrieve request the file will not be automatically downloaded, you can then access the result location (the URL to the file) and download it using your own methods. For example, here I make the request then download the result using wget:

```
import cdsapi
cds = cdsapi.Client()
result = cds.retrieve('reanalysis-era5-pressure-levels', {
           "variable": "temperature",
           "pressure_level": "1000",
           "product_type": "reanalysis",
           "date": "2017-12-01/2017-12-31",
           "time": "12:00",
           "format": "grib"
       })

print(result.location)

import wget
wget.download(result.location)
```

As we do not have any SSL cert issues at present it is not possible for me to fully check this method, but I hope it serves as a nice demonstrator.

Eddy

**Comment by Nyu13** [comment] 2023-10-26 15:48
I have same problem for last week. server 0003 doesn't work too... 
WARNING Connection error: [HTTPSConnectionPool(host='download-0003-clone.copernicus-climate.eu', port=443)

**Comment by Nyu13** [comment] 2023-10-26 15:50
c = cdsapi.Client(timeout=600,quiet=False,debug=True)

# Variable and Year of Interest
V = [
                '100m_u_component_of_wind','100m_v_component_of_wind'
    ]
Y = '2022'

# Constructing the filename for the download
target_filename = f'era5-hourly-{Y}.grib'

# Check if the file already exists to avoid re-downloading
if not os.path.isfile(target_filename):
    c.retrieve(
        'reanalysis-era5-single-levels',
        {
            'variable': V,
            'product_type': 'reanalysis',
            'year': Y,
            'month': [
                '01', '02', '03', '04', '05', '06',
                '07', '08', '09', '10', '11', '12'
            ],
            'day': [
                '01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
                '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
                '31'
            ],
            'time': [
                '00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
                '06:00', '07:00', '08:00', '09:00', '10:00', '11:00',
                '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                '18:00', '19:00', '20:00', '21:00', '22:00', '23:00'
            ],
            'format': 'grib',
            'area': [
                60, -65, 46,
                -51,
            ],
        },
        target_filename
    )
